// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cut.dart';
import 'api/gcode.dart';
import 'api/sender.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.10.0';

  @override
  int get rustContentHash => 2140841411;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutter_tube_cutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  double crateApiCutCutAutoAccessorGetCutAngle({required Cut that});

  double crateApiCutCutAutoAccessorGetCutFeedrate({required Cut that});

  Pos2D crateApiCutCutAutoAccessorGetEndPosition({required Cut that});

  double crateApiCutCutAutoAccessorGetPierceDelay({required Cut that});

  Pos2D crateApiCutCutAutoAccessorGetStartPosition({required Cut that});

  double crateApiCutCutAutoAccessorGetTubeWidth({required Cut that});

  void crateApiCutCutAutoAccessorSetCutAngle({
    required Cut that,
    required double cutAngle,
  });

  void crateApiCutCutAutoAccessorSetCutFeedrate({
    required Cut that,
    required double cutFeedrate,
  });

  void crateApiCutCutAutoAccessorSetEndPosition({
    required Cut that,
    required Pos2D endPosition,
  });

  void crateApiCutCutAutoAccessorSetPierceDelay({
    required Cut that,
    required double pierceDelay,
  });

  void crateApiCutCutAutoAccessorSetStartPosition({
    required Cut that,
    required Pos2D startPosition,
  });

  void crateApiCutCutAutoAccessorSetTubeWidth({
    required Cut that,
    required double tubeWidth,
  });

  (double, double) crateApiCutCutGetEndPos({required Cut that});

  Cut crateApiCutCutNew();

  void crateApiCutCutSetCutAngle({required Cut that, required double newAngle});

  void crateApiCutCutSetCutFeedrate({
    required Cut that,
    required double newFeedrate,
  });

  void crateApiCutCutSetPierceDelay({
    required Cut that,
    required double newDelay,
  });

  void crateApiCutCutSetTubeWidth({
    required Cut that,
    required double newWidth,
  });

  Future<void> crateApiGcodeGcodeAddCommand({
    required Gcode that,
    required String gCommand,
  });

  Future<void> crateApiGcodeGcodeAddCommandComment({
    required Gcode that,
    required String gCommand,
    required String gComment,
  });

  void crateApiGcodeGcodeAddCut({required Gcode that, required Cut tubeCut});

  String crateApiGcodeGcodeAutoAccessorGetGcodeString({required Gcode that});

  void crateApiGcodeGcodeAutoAccessorSetGcodeString({
    required Gcode that,
    required String gcodeString,
  });

  Future<void> crateApiGcodeGcodeDwell({
    required Gcode that,
    required double dwellTime,
  });

  String crateApiGcodeGcodeGetGcodeString({required Gcode that});

  Future<void> crateApiGcodeGcodeHome2D({
    required Gcode that,
    required double feedrate,
  });

  Future<void> crateApiGcodeGcodeMoveXy({
    required Gcode that,
    required Pos2D newPos,
    required double feedrate,
  });

  Gcode crateApiGcodeGcodeNew();

  Future<void> crateApiGcodeGcodeSetPlasmaEnabled({
    required Gcode that,
    required bool enabled,
  });

  Future<void> crateApiGcodeGcodeSetPositioningMode({
    required Gcode that,
    required PositioningMode positioningMode,
  });

  Future<void> crateApiGcodeGcodeSetZero({required Gcode that});

  Future<void> crateApiGcodeGcodeWriteToFile({
    required Gcode that,
    required String filename,
  });

  void crateApiSenderMachineConnectionHome({required MachineConnection that});

  void crateApiSenderMachineConnectionMakeConnection({
    required MachineConnection that,
  });

  MachineConnection crateApiSenderMachineConnectionNew();

  void crateApiSenderMachineConnectionSendGcodeCommand({
    required MachineConnection that,
    required String command,
  });

  void crateApiSenderMachineConnectionSendStringCommand({
    required MachineConnection that,
    required String command,
  });

  void crateApiSenderMachineConnectionSendStringCommandLowPriority({
    required MachineConnection that,
    required String command,
  });

  void crateApiSenderMachineConnectionSetSerialPort({
    required MachineConnection that,
    required String newPort,
  });

  double crateApiGcodePos2DAutoAccessorGetX({required Pos2D that});

  double crateApiGcodePos2DAutoAccessorGetY({required Pos2D that});

  void crateApiGcodePos2DAutoAccessorSetX({
    required Pos2D that,
    required double x,
  });

  void crateApiGcodePos2DAutoAccessorSetY({
    required Pos2D that,
    required double y,
  });

  Future<Pos2D> crateApiGcodePos2DNew({required double x, required double y});

  Future<Pos2D> crateApiGcodePos2DToScreenSpace({
    required Pos2D that,
    required double tubeWidth,
    required double scaleFactor,
  });

  Future<Pos2D> crateApiGcodeCalculateEndPos({
    required Pos2D startPos,
    required double tubeWidth,
    required double cutAngle,
    required double overshootAmount,
    required bool cutRight,
  });

  Future<Pos2D> crateApiGcodeGetMidpoint({
    required Pos2D startPos,
    required Pos2D endPos,
  });

  List<String> crateApiSimpleGetSerialPorts();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  String crateApiGcodeJog({required double xDist, required double yDist});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Cut;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Cut;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CutPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Gcode;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Gcode;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_GcodePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MachineConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MachineConnection;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MachineConnectionPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Pos2D;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Pos2D;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Pos2DPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  double crateApiCutCutAutoAccessorGetCutAngle({required Cut that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorGetCutAngleConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorGetCutAngleConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_get_cut_angle",
        argNames: ["that"],
      );

  @override
  double crateApiCutCutAutoAccessorGetCutFeedrate({required Cut that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorGetCutFeedrateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorGetCutFeedrateConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_get_cut_feedrate",
        argNames: ["that"],
      );

  @override
  Pos2D crateApiCutCutAutoAccessorGetEndPosition({required Cut that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorGetEndPositionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorGetEndPositionConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_get_end_position",
        argNames: ["that"],
      );

  @override
  double crateApiCutCutAutoAccessorGetPierceDelay({required Cut that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorGetPierceDelayConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorGetPierceDelayConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_get_pierce_delay",
        argNames: ["that"],
      );

  @override
  Pos2D crateApiCutCutAutoAccessorGetStartPosition({required Cut that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorGetStartPositionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorGetStartPositionConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_get_start_position",
        argNames: ["that"],
      );

  @override
  double crateApiCutCutAutoAccessorGetTubeWidth({required Cut that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorGetTubeWidthConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorGetTubeWidthConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_get_tube_width",
        argNames: ["that"],
      );

  @override
  void crateApiCutCutAutoAccessorSetCutAngle({
    required Cut that,
    required double cutAngle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          sse_encode_f_32(cutAngle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorSetCutAngleConstMeta,
        argValues: [that, cutAngle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorSetCutAngleConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_set_cut_angle",
        argNames: ["that", "cutAngle"],
      );

  @override
  void crateApiCutCutAutoAccessorSetCutFeedrate({
    required Cut that,
    required double cutFeedrate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          sse_encode_f_32(cutFeedrate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorSetCutFeedrateConstMeta,
        argValues: [that, cutFeedrate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorSetCutFeedrateConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_set_cut_feedrate",
        argNames: ["that", "cutFeedrate"],
      );

  @override
  void crateApiCutCutAutoAccessorSetEndPosition({
    required Cut that,
    required Pos2D endPosition,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            endPosition,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorSetEndPositionConstMeta,
        argValues: [that, endPosition],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorSetEndPositionConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_set_end_position",
        argNames: ["that", "endPosition"],
      );

  @override
  void crateApiCutCutAutoAccessorSetPierceDelay({
    required Cut that,
    required double pierceDelay,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          sse_encode_f_32(pierceDelay, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorSetPierceDelayConstMeta,
        argValues: [that, pierceDelay],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorSetPierceDelayConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_set_pierce_delay",
        argNames: ["that", "pierceDelay"],
      );

  @override
  void crateApiCutCutAutoAccessorSetStartPosition({
    required Cut that,
    required Pos2D startPosition,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            startPosition,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorSetStartPositionConstMeta,
        argValues: [that, startPosition],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorSetStartPositionConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_set_start_position",
        argNames: ["that", "startPosition"],
      );

  @override
  void crateApiCutCutAutoAccessorSetTubeWidth({
    required Cut that,
    required double tubeWidth,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          sse_encode_f_32(tubeWidth, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutAutoAccessorSetTubeWidthConstMeta,
        argValues: [that, tubeWidth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutAutoAccessorSetTubeWidthConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_auto_accessor_set_tube_width",
        argNames: ["that", "tubeWidth"],
      );

  @override
  (double, double) crateApiCutCutGetEndPos({required Cut that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_f_32_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutGetEndPosConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutGetEndPosConstMeta =>
      const TaskConstMeta(debugName: "Cut_get_end_pos", argNames: ["that"]);

  @override
  Cut crateApiCutCutNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutNewConstMeta =>
      const TaskConstMeta(debugName: "Cut_new", argNames: []);

  @override
  void crateApiCutCutSetCutAngle({
    required Cut that,
    required double newAngle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          sse_encode_f_32(newAngle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutSetCutAngleConstMeta,
        argValues: [that, newAngle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutSetCutAngleConstMeta => const TaskConstMeta(
    debugName: "Cut_set_cut_angle",
    argNames: ["that", "newAngle"],
  );

  @override
  void crateApiCutCutSetCutFeedrate({
    required Cut that,
    required double newFeedrate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          sse_encode_f_32(newFeedrate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutSetCutFeedrateConstMeta,
        argValues: [that, newFeedrate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutSetCutFeedrateConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_set_cut_feedrate",
        argNames: ["that", "newFeedrate"],
      );

  @override
  void crateApiCutCutSetPierceDelay({
    required Cut that,
    required double newDelay,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          sse_encode_f_32(newDelay, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutSetPierceDelayConstMeta,
        argValues: [that, newDelay],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutSetPierceDelayConstMeta =>
      const TaskConstMeta(
        debugName: "Cut_set_pierce_delay",
        argNames: ["that", "newDelay"],
      );

  @override
  void crateApiCutCutSetTubeWidth({
    required Cut that,
    required double newWidth,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            that,
            serializer,
          );
          sse_encode_f_32(newWidth, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCutCutSetTubeWidthConstMeta,
        argValues: [that, newWidth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCutCutSetTubeWidthConstMeta => const TaskConstMeta(
    debugName: "Cut_set_tube_width",
    argNames: ["that", "newWidth"],
  );

  @override
  Future<void> crateApiGcodeGcodeAddCommand({
    required Gcode that,
    required String gCommand,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          sse_encode_String(gCommand, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeAddCommandConstMeta,
        argValues: [that, gCommand],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeAddCommandConstMeta =>
      const TaskConstMeta(
        debugName: "Gcode_add_command",
        argNames: ["that", "gCommand"],
      );

  @override
  Future<void> crateApiGcodeGcodeAddCommandComment({
    required Gcode that,
    required String gCommand,
    required String gComment,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          sse_encode_String(gCommand, serializer);
          sse_encode_String(gComment, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeAddCommandCommentConstMeta,
        argValues: [that, gCommand, gComment],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeAddCommandCommentConstMeta =>
      const TaskConstMeta(
        debugName: "Gcode_add_command_comment",
        argNames: ["that", "gCommand", "gComment"],
      );

  @override
  void crateApiGcodeGcodeAddCut({required Gcode that, required Cut tubeCut}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
            tubeCut,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeAddCutConstMeta,
        argValues: [that, tubeCut],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeAddCutConstMeta => const TaskConstMeta(
    debugName: "Gcode_add_cut",
    argNames: ["that", "tubeCut"],
  );

  @override
  String crateApiGcodeGcodeAutoAccessorGetGcodeString({required Gcode that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeAutoAccessorGetGcodeStringConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeAutoAccessorGetGcodeStringConstMeta =>
      const TaskConstMeta(
        debugName: "Gcode_auto_accessor_get_gcode_string",
        argNames: ["that"],
      );

  @override
  void crateApiGcodeGcodeAutoAccessorSetGcodeString({
    required Gcode that,
    required String gcodeString,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          sse_encode_String(gcodeString, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeAutoAccessorSetGcodeStringConstMeta,
        argValues: [that, gcodeString],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeAutoAccessorSetGcodeStringConstMeta =>
      const TaskConstMeta(
        debugName: "Gcode_auto_accessor_set_gcode_string",
        argNames: ["that", "gcodeString"],
      );

  @override
  Future<void> crateApiGcodeGcodeDwell({
    required Gcode that,
    required double dwellTime,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          sse_encode_f_32(dwellTime, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeDwellConstMeta,
        argValues: [that, dwellTime],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeDwellConstMeta => const TaskConstMeta(
    debugName: "Gcode_dwell",
    argNames: ["that", "dwellTime"],
  );

  @override
  String crateApiGcodeGcodeGetGcodeString({required Gcode that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeGetGcodeStringConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeGetGcodeStringConstMeta =>
      const TaskConstMeta(
        debugName: "Gcode_get_gcode_string",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiGcodeGcodeHome2D({
    required Gcode that,
    required double feedrate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          sse_encode_f_32(feedrate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeHome2DConstMeta,
        argValues: [that, feedrate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeHome2DConstMeta => const TaskConstMeta(
    debugName: "Gcode_home2D",
    argNames: ["that", "feedrate"],
  );

  @override
  Future<void> crateApiGcodeGcodeMoveXy({
    required Gcode that,
    required Pos2D newPos,
    required double feedrate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            newPos,
            serializer,
          );
          sse_encode_f_32(feedrate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeMoveXyConstMeta,
        argValues: [that, newPos, feedrate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeMoveXyConstMeta => const TaskConstMeta(
    debugName: "Gcode_move_xy",
    argNames: ["that", "newPos", "feedrate"],
  );

  @override
  Gcode crateApiGcodeGcodeNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeNewConstMeta =>
      const TaskConstMeta(debugName: "Gcode_new", argNames: []);

  @override
  Future<void> crateApiGcodeGcodeSetPlasmaEnabled({
    required Gcode that,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeSetPlasmaEnabledConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeSetPlasmaEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "Gcode_set_plasma_enabled",
        argNames: ["that", "enabled"],
      );

  @override
  Future<void> crateApiGcodeGcodeSetPositioningMode({
    required Gcode that,
    required PositioningMode positioningMode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          sse_encode_positioning_mode(positioningMode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeSetPositioningModeConstMeta,
        argValues: [that, positioningMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeSetPositioningModeConstMeta =>
      const TaskConstMeta(
        debugName: "Gcode_set_positioning_mode",
        argNames: ["that", "positioningMode"],
      );

  @override
  Future<void> crateApiGcodeGcodeSetZero({required Gcode that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeSetZeroConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeSetZeroConstMeta =>
      const TaskConstMeta(debugName: "Gcode_set_zero", argNames: ["that"]);

  @override
  Future<void> crateApiGcodeGcodeWriteToFile({
    required Gcode that,
    required String filename,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
            that,
            serializer,
          );
          sse_encode_String(filename, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGcodeWriteToFileConstMeta,
        argValues: [that, filename],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGcodeWriteToFileConstMeta =>
      const TaskConstMeta(
        debugName: "Gcode_write_to_file",
        argNames: ["that", "filename"],
      );

  @override
  void crateApiSenderMachineConnectionHome({required MachineConnection that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSenderMachineConnectionHomeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderMachineConnectionHomeConstMeta =>
      const TaskConstMeta(
        debugName: "MachineConnection_home",
        argNames: ["that"],
      );

  @override
  void crateApiSenderMachineConnectionMakeConnection({
    required MachineConnection that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSenderMachineConnectionMakeConnectionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderMachineConnectionMakeConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "MachineConnection_make_connection",
        argNames: ["that"],
      );

  @override
  MachineConnection crateApiSenderMachineConnectionNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSenderMachineConnectionNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderMachineConnectionNewConstMeta =>
      const TaskConstMeta(debugName: "MachineConnection_new", argNames: []);

  @override
  void crateApiSenderMachineConnectionSendGcodeCommand({
    required MachineConnection that,
    required String command,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
            that,
            serializer,
          );
          sse_encode_String(command, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSenderMachineConnectionSendGcodeCommandConstMeta,
        argValues: [that, command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderMachineConnectionSendGcodeCommandConstMeta =>
      const TaskConstMeta(
        debugName: "MachineConnection_send_gcode_command",
        argNames: ["that", "command"],
      );

  @override
  void crateApiSenderMachineConnectionSendStringCommand({
    required MachineConnection that,
    required String command,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
            that,
            serializer,
          );
          sse_encode_String(command, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSenderMachineConnectionSendStringCommandConstMeta,
        argValues: [that, command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSenderMachineConnectionSendStringCommandConstMeta =>
      const TaskConstMeta(
        debugName: "MachineConnection_send_string_command",
        argNames: ["that", "command"],
      );

  @override
  void crateApiSenderMachineConnectionSendStringCommandLowPriority({
    required MachineConnection that,
    required String command,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
            that,
            serializer,
          );
          sse_encode_String(command, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiSenderMachineConnectionSendStringCommandLowPriorityConstMeta,
        argValues: [that, command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSenderMachineConnectionSendStringCommandLowPriorityConstMeta =>
      const TaskConstMeta(
        debugName: "MachineConnection_send_string_command_low_priority",
        argNames: ["that", "command"],
      );

  @override
  void crateApiSenderMachineConnectionSetSerialPort({
    required MachineConnection that,
    required String newPort,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
            that,
            serializer,
          );
          sse_encode_String(newPort, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSenderMachineConnectionSetSerialPortConstMeta,
        argValues: [that, newPort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderMachineConnectionSetSerialPortConstMeta =>
      const TaskConstMeta(
        debugName: "MachineConnection_set_serial_port",
        argNames: ["that", "newPort"],
      );

  @override
  double crateApiGcodePos2DAutoAccessorGetX({required Pos2D that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodePos2DAutoAccessorGetXConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodePos2DAutoAccessorGetXConstMeta =>
      const TaskConstMeta(
        debugName: "Pos2D_auto_accessor_get_x",
        argNames: ["that"],
      );

  @override
  double crateApiGcodePos2DAutoAccessorGetY({required Pos2D that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 41)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodePos2DAutoAccessorGetYConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodePos2DAutoAccessorGetYConstMeta =>
      const TaskConstMeta(
        debugName: "Pos2D_auto_accessor_get_y",
        argNames: ["that"],
      );

  @override
  void crateApiGcodePos2DAutoAccessorSetX({
    required Pos2D that,
    required double x,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            that,
            serializer,
          );
          sse_encode_f_32(x, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodePos2DAutoAccessorSetXConstMeta,
        argValues: [that, x],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodePos2DAutoAccessorSetXConstMeta =>
      const TaskConstMeta(
        debugName: "Pos2D_auto_accessor_set_x",
        argNames: ["that", "x"],
      );

  @override
  void crateApiGcodePos2DAutoAccessorSetY({
    required Pos2D that,
    required double y,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            that,
            serializer,
          );
          sse_encode_f_32(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodePos2DAutoAccessorSetYConstMeta,
        argValues: [that, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodePos2DAutoAccessorSetYConstMeta =>
      const TaskConstMeta(
        debugName: "Pos2D_auto_accessor_set_y",
        argNames: ["that", "y"],
      );

  @override
  Future<Pos2D> crateApiGcodePos2DNew({required double x, required double y}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodePos2DNewConstMeta,
        argValues: [x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodePos2DNewConstMeta =>
      const TaskConstMeta(debugName: "Pos2D_new", argNames: ["x", "y"]);

  @override
  Future<Pos2D> crateApiGcodePos2DToScreenSpace({
    required Pos2D that,
    required double tubeWidth,
    required double scaleFactor,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            that,
            serializer,
          );
          sse_encode_f_32(tubeWidth, serializer);
          sse_encode_f_32(scaleFactor, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodePos2DToScreenSpaceConstMeta,
        argValues: [that, tubeWidth, scaleFactor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodePos2DToScreenSpaceConstMeta =>
      const TaskConstMeta(
        debugName: "Pos2D_to_screen_space",
        argNames: ["that", "tubeWidth", "scaleFactor"],
      );

  @override
  Future<Pos2D> crateApiGcodeCalculateEndPos({
    required Pos2D startPos,
    required double tubeWidth,
    required double cutAngle,
    required double overshootAmount,
    required bool cutRight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            startPos,
            serializer,
          );
          sse_encode_f_32(tubeWidth, serializer);
          sse_encode_f_32(cutAngle, serializer);
          sse_encode_f_32(overshootAmount, serializer);
          sse_encode_bool(cutRight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeCalculateEndPosConstMeta,
        argValues: [startPos, tubeWidth, cutAngle, overshootAmount, cutRight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeCalculateEndPosConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_end_pos",
        argNames: [
          "startPos",
          "tubeWidth",
          "cutAngle",
          "overshootAmount",
          "cutRight",
        ],
      );

  @override
  Future<Pos2D> crateApiGcodeGetMidpoint({
    required Pos2D startPos,
    required Pos2D endPos,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            startPos,
            serializer,
          );
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
            endPos,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 47,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeGetMidpointConstMeta,
        argValues: [startPos, endPos],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeGetMidpointConstMeta => const TaskConstMeta(
    debugName: "get_midpoint",
    argNames: ["startPos", "endPos"],
  );

  @override
  List<String> crateApiSimpleGetSerialPorts() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 48)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetSerialPortsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetSerialPortsConstMeta =>
      const TaskConstMeta(debugName: "get_serial_ports", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 49)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  String crateApiGcodeJog({required double xDist, required double yDist}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(xDist, serializer);
          sse_encode_f_32(yDist, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 51)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGcodeJogConstMeta,
        argValues: [xDist, yDist],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGcodeJogConstMeta =>
      const TaskConstMeta(debugName: "jog", argNames: ["xDist", "yDist"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Cut => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Cut => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Gcode => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Gcode => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MachineConnection => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MachineConnection => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Pos2D => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Pos2D => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D;

  @protected
  Cut
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CutImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Gcode
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GcodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MachineConnection
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MachineConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Pos2D
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Pos2DImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Cut
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CutImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Gcode
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GcodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MachineConnection
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MachineConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Pos2D
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Pos2DImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Cut
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CutImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Gcode
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GcodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MachineConnection
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MachineConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Pos2D
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Pos2DImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Cut
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CutImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Gcode
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GcodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MachineConnection
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MachineConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Pos2D
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Pos2DImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PositioningMode dco_decode_positioning_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PositioningMode.values[raw as int];
  }

  @protected
  (double, double) dco_decode_record_f_32_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_f_32(arr[0]), dco_decode_f_32(arr[1]));
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Cut
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CutImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Gcode
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GcodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MachineConnection
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MachineConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Pos2D
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Pos2DImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Cut
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CutImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Gcode
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GcodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MachineConnection
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MachineConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Pos2D
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Pos2DImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Cut
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CutImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Gcode
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GcodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MachineConnection
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MachineConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Pos2D
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Pos2DImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Cut
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CutImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Gcode
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GcodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MachineConnection
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MachineConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Pos2D
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Pos2DImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PositioningMode sse_decode_positioning_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PositioningMode.values[inner];
  }

  @protected
  (double, double) sse_decode_record_f_32_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_32(deserializer);
    var var_field1 = sse_decode_f_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    Cut self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CutImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    Gcode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GcodeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    MachineConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MachineConnectionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    Pos2D self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Pos2DImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    Cut self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CutImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    Gcode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GcodeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    MachineConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MachineConnectionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    Pos2D self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Pos2DImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    Cut self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CutImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    Gcode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GcodeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    MachineConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MachineConnectionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    Pos2D self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Pos2DImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCut(
    Cut self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CutImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGcode(
    Gcode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GcodeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMachineConnection(
    MachineConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MachineConnectionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPos2D(
    Pos2D self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Pos2DImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_positioning_mode(
    PositioningMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_record_f_32_f_32(
    (double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.$1, serializer);
    sse_encode_f_32(self.$2, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class CutImpl extends RustOpaque implements Cut {
  // Not to be used by end users
  CutImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CutImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Cut,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Cut,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CutPtr,
  );

  double get cutAngle =>
      RustLib.instance.api.crateApiCutCutAutoAccessorGetCutAngle(that: this);

  double get cutFeedrate =>
      RustLib.instance.api.crateApiCutCutAutoAccessorGetCutFeedrate(that: this);

  Pos2D get endPosition =>
      RustLib.instance.api.crateApiCutCutAutoAccessorGetEndPosition(that: this);

  double get pierceDelay =>
      RustLib.instance.api.crateApiCutCutAutoAccessorGetPierceDelay(that: this);

  Pos2D get startPosition => RustLib.instance.api
      .crateApiCutCutAutoAccessorGetStartPosition(that: this);

  double get tubeWidth =>
      RustLib.instance.api.crateApiCutCutAutoAccessorGetTubeWidth(that: this);

  set cutAngle(double cutAngle) => RustLib.instance.api
      .crateApiCutCutAutoAccessorSetCutAngle(that: this, cutAngle: cutAngle);

  set cutFeedrate(double cutFeedrate) =>
      RustLib.instance.api.crateApiCutCutAutoAccessorSetCutFeedrate(
        that: this,
        cutFeedrate: cutFeedrate,
      );

  set endPosition(Pos2D endPosition) =>
      RustLib.instance.api.crateApiCutCutAutoAccessorSetEndPosition(
        that: this,
        endPosition: endPosition,
      );

  set pierceDelay(double pierceDelay) =>
      RustLib.instance.api.crateApiCutCutAutoAccessorSetPierceDelay(
        that: this,
        pierceDelay: pierceDelay,
      );

  set startPosition(Pos2D startPosition) =>
      RustLib.instance.api.crateApiCutCutAutoAccessorSetStartPosition(
        that: this,
        startPosition: startPosition,
      );

  set tubeWidth(double tubeWidth) => RustLib.instance.api
      .crateApiCutCutAutoAccessorSetTubeWidth(that: this, tubeWidth: tubeWidth);

  (double, double) getEndPos() =>
      RustLib.instance.api.crateApiCutCutGetEndPos(that: this);

  void setCutAngle({required double newAngle}) => RustLib.instance.api
      .crateApiCutCutSetCutAngle(that: this, newAngle: newAngle);

  void setCutFeedrate({required double newFeedrate}) => RustLib.instance.api
      .crateApiCutCutSetCutFeedrate(that: this, newFeedrate: newFeedrate);

  void setPierceDelay({required double newDelay}) => RustLib.instance.api
      .crateApiCutCutSetPierceDelay(that: this, newDelay: newDelay);

  void setTubeWidth({required double newWidth}) => RustLib.instance.api
      .crateApiCutCutSetTubeWidth(that: this, newWidth: newWidth);
}

@sealed
class GcodeImpl extends RustOpaque implements Gcode {
  // Not to be used by end users
  GcodeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  GcodeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Gcode,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Gcode,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_GcodePtr,
  );

  Future<void> addCommand({required String gCommand}) => RustLib.instance.api
      .crateApiGcodeGcodeAddCommand(that: this, gCommand: gCommand);

  Future<void> addCommandComment({
    required String gCommand,
    required String gComment,
  }) => RustLib.instance.api.crateApiGcodeGcodeAddCommandComment(
    that: this,
    gCommand: gCommand,
    gComment: gComment,
  );

  void addCut({required Cut tubeCut}) => RustLib.instance.api
      .crateApiGcodeGcodeAddCut(that: this, tubeCut: tubeCut);

  String get gcodeString => RustLib.instance.api
      .crateApiGcodeGcodeAutoAccessorGetGcodeString(that: this);

  set gcodeString(String gcodeString) =>
      RustLib.instance.api.crateApiGcodeGcodeAutoAccessorSetGcodeString(
        that: this,
        gcodeString: gcodeString,
      );

  Future<void> dwell({required double dwellTime}) => RustLib.instance.api
      .crateApiGcodeGcodeDwell(that: this, dwellTime: dwellTime);

  String getGcodeString() =>
      RustLib.instance.api.crateApiGcodeGcodeGetGcodeString(that: this);

  Future<void> home2D({required double feedrate}) => RustLib.instance.api
      .crateApiGcodeGcodeHome2D(that: this, feedrate: feedrate);

  Future<void> moveXy({required Pos2D newPos, required double feedrate}) =>
      RustLib.instance.api.crateApiGcodeGcodeMoveXy(
        that: this,
        newPos: newPos,
        feedrate: feedrate,
      );

  Future<void> setPlasmaEnabled({required bool enabled}) => RustLib.instance.api
      .crateApiGcodeGcodeSetPlasmaEnabled(that: this, enabled: enabled);

  Future<void> setPositioningMode({required PositioningMode positioningMode}) =>
      RustLib.instance.api.crateApiGcodeGcodeSetPositioningMode(
        that: this,
        positioningMode: positioningMode,
      );

  Future<void> setZero() =>
      RustLib.instance.api.crateApiGcodeGcodeSetZero(that: this);

  Future<void> writeToFile({required String filename}) => RustLib.instance.api
      .crateApiGcodeGcodeWriteToFile(that: this, filename: filename);
}

@sealed
class MachineConnectionImpl extends RustOpaque implements MachineConnection {
  // Not to be used by end users
  MachineConnectionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MachineConnectionImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MachineConnection,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MachineConnection,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_MachineConnectionPtr,
  );

  void home() =>
      RustLib.instance.api.crateApiSenderMachineConnectionHome(that: this);

  void makeConnection() => RustLib.instance.api
      .crateApiSenderMachineConnectionMakeConnection(that: this);

  void sendGcodeCommand({required String command}) =>
      RustLib.instance.api.crateApiSenderMachineConnectionSendGcodeCommand(
        that: this,
        command: command,
      );

  void sendStringCommand({required String command}) =>
      RustLib.instance.api.crateApiSenderMachineConnectionSendStringCommand(
        that: this,
        command: command,
      );

  void sendStringCommandLowPriority({required String command}) => RustLib
      .instance
      .api
      .crateApiSenderMachineConnectionSendStringCommandLowPriority(
        that: this,
        command: command,
      );

  void setSerialPort({required String newPort}) =>
      RustLib.instance.api.crateApiSenderMachineConnectionSetSerialPort(
        that: this,
        newPort: newPort,
      );
}

@sealed
class Pos2DImpl extends RustOpaque implements Pos2D {
  // Not to be used by end users
  Pos2DImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Pos2DImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Pos2D,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Pos2D,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_Pos2DPtr,
  );

  double get x =>
      RustLib.instance.api.crateApiGcodePos2DAutoAccessorGetX(that: this);

  double get y =>
      RustLib.instance.api.crateApiGcodePos2DAutoAccessorGetY(that: this);

  set x(double x) =>
      RustLib.instance.api.crateApiGcodePos2DAutoAccessorSetX(that: this, x: x);

  set y(double y) =>
      RustLib.instance.api.crateApiGcodePos2DAutoAccessorSetY(that: this, y: y);

  Future<Pos2D> toScreenSpace({
    required double tubeWidth,
    required double scaleFactor,
  }) => RustLib.instance.api.crateApiGcodePos2DToScreenSpace(
    that: this,
    tubeWidth: tubeWidth,
    scaleFactor: scaleFactor,
  );
}
