// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'gcode.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Cut>>
abstract class Cut implements RustOpaqueInterface {
  double get cutAngle;

  double get cutFeedrate;

  Pos2D get endPosition;

  double get pierceDelay;

  Pos2D get startPosition;

  double get tubeWidth;

  set cutAngle(double cutAngle);

  set cutFeedrate(double cutFeedrate);

  set endPosition(Pos2D endPosition);

  set pierceDelay(double pierceDelay);

  set startPosition(Pos2D startPosition);

  set tubeWidth(double tubeWidth);

  factory Cut() => RustLib.instance.api.crateApiCutCutNew();

  void setCutAngle({required double newAngle});

  void setCutFeedrate({required double newFeedrate});

  void setPierceDelay({required double newDelay});

  void setTubeWidth({required double newWidth});
}
