// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'settings.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MachineCommand`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MachineConnection>>
abstract class MachineConnection implements RustOpaqueInterface {
  void home({required CutterSettings cutterSettings});

  Stream<MachinePosition> makeConnection();

  factory MachineConnection() =>
      RustLib.instance.api.crateApiSenderMachineConnectionNew();

  void sendGcodeCommand({required String command});

  void sendStringCommand({required String command});

  void sendStringCommandLowPriority({required String command});

  void setSerialPort({required String newPort});
}

class MachinePosition {
  final double x;
  final double y;

  const MachinePosition.raw({required this.x, required this.y});

  factory MachinePosition() =>
      RustLib.instance.api.crateApiSenderMachinePositionNew();

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MachinePosition &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}
