// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CutMethod>>
abstract class CutMethod implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CutterSettings>>
abstract class CutterSettings implements RustOpaqueInterface {
  CutMethod get cutMethod;

  double get laserOffsetX;

  double get laserOffsetY;

  bool get useLaser;

  set cutMethod(CutMethod cutMethod);

  set laserOffsetX(double laserOffsetX);

  set laserOffsetY(double laserOffsetY);

  set useLaser(bool useLaser);

  static CutterSettings load() =>
      RustLib.instance.api.crateApiSettingsCutterSettingsLoad();

  factory CutterSettings() =>
      RustLib.instance.api.crateApiSettingsCutterSettingsNew();

  void save();
}
